# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTNO', models.IntegerField(default=0)),
                ('STARTDATE', models.DateTimeField(verbose_name='start date')),
                ('ENDDATE', models.DateTimeField(verbose_name='start date')),
                ('IPDOPD', models.CharField(max_length=1)),
                ('DEPTCODE', models.CharField(max_length=1024)),
                ('WRITEDEPT', models.CharField(max_length=1024)),
                ('WRITEDRCODE', models.IntegerField(default=0)),
                ('DXCODE', models.CharField(max_length=1024)),
                ('SPCKIHO', models.CharField(max_length=1024)),
                ('PRESENTSYMTOM', models.IntegerField(default=0)),
                ('DXMOREFLAG', models.IntegerField(default=0)),
                ('PRESCRIPTIONLIST', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTNO', models.IntegerField(default=0)),
                ('ORDERDATE', models.DateTimeField(verbose_name='order date')),
                ('IPDOPD', models.CharField(max_length=1)),
                ('DEPTCODE', models.CharField(max_length=1024)),
                ('ORDERCLASS', models.IntegerField(default=0)),
                ('ORDERGROUP', models.IntegerField(default=0)),
                ('SLIPNUM', models.IntegerField(default=0)),
                ('BUN', models.IntegerField(default=0)),
                ('BUNDETAIL', models.IntegerField(default=0)),
                ('ORDERCODE', models.CharField(max_length=1024)),
                ('ORDERNAME', models.CharField(max_length=1024)),
                ('SUCODE', models.CharField(max_length=1024)),
                ('BCODE', models.CharField(max_length=1024)),
                ('SELFFLAG', models.IntegerField(default=0)),
            ],
        ),
    ]
