# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode', models.CharField(max_length=1024)),
                ('prescriptionlist', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icdcode', models.CharField(max_length=1024)),
                ('fullcode', models.CharField(max_length=1024)),
                ('namek', models.CharField(max_length=1024)),
                ('namee', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(max_length=128)),
                ('ordername', models.CharField(max_length=1024)),
            ],
        ),
    ]
