# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disease',
            name='ENDDATE',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='STARTDATE',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
