# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(max_length=128)),
                ('dxcode', models.CharField(max_length=1024)),
                ('frequency', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(max_length=128)),
                ('ordername', models.CharField(max_length=1024)),
                ('notice_description', models.CharField(max_length=1024)),
                ('display_condition', models.BooleanField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercode', models.CharField(max_length=128)),
                ('dxcode', models.CharField(max_length=1024)),
                ('frequency', models.CharField(max_length=16)),
            ],
        ),
    ]
