# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0002_auto_20170926_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='index',
        ),
        migrations.AlterField(
            model_name='disease',
            name='ENDDATE',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='disease',
            name='STARTDATE',
            field=models.CharField(max_length=1),
        ),
    ]
