# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0002_doctor_diagnose_notice_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
