# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0003_auto_20171207_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctor_diagnose',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
