# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0003_auto_20170926_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
