# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0004_delete_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTNO', models.IntegerField(default=0)),
                ('STARTDATE', models.CharField(max_length=1)),
                ('ENDDATE', models.CharField(max_length=1)),
                ('IPDOPD', models.CharField(max_length=1)),
                ('DEPTCODE', models.CharField(max_length=1024)),
                ('WRITEDEPT', models.CharField(max_length=1024)),
                ('WRITEDRCODE', models.IntegerField(default=0)),
                ('DXCODE', models.CharField(max_length=1024)),
                ('SPCKIHO', models.CharField(max_length=1024)),
                ('PRESENTSYMTOM', models.IntegerField(default=0)),
                ('DXMOREFLAG', models.IntegerField(default=0)),
                ('PRESCRIPTIONLIST', models.CharField(max_length=4096)),
            ],
        ),
    ]
