# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0004_auto_20180109_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='fileflag',
            field=models.BooleanField(default=True),
        ),
    ]
