# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0005_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERCODE', models.CharField(max_length=128)),
            ],
        ),
    ]
