# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0005_disease_fileflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='usedflag',
            field=models.BooleanField(default=False),
        ),
    ]
