# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0006_uploadfilemodel_usedflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemodelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
