# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0006_prescription_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPDOPD', models.CharField(max_length=1024)),
                ('DXCODE', models.CharField(max_length=1024)),
                ('ORDERCLASS', models.CharField(max_length=1024)),
                ('ORDERCODE', models.CharField(max_length=1024)),
                ('ORDERNAME', models.CharField(max_length=1024)),
                ('DXCODECOUNT', models.IntegerField(default=0)),
                ('DATECOUNT', models.IntegerField(default=0)),
            ],
        ),
    ]
