# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0007_remodeltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='remodeltime',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 17, 29, 31, 246033)),
        ),
        migrations.AddField(
            model_name='remodeltime',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
