# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0008_auto_20180125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remodeltime',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 17, 32, 14, 445875)),
        ),
        migrations.AlterField(
            model_name='remodeltime',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 17, 32, 14, 445851)),
        ),
    ]
